### ISSUE TITLE
Fix Dockerfile generator: Update CMD to use Uvicorn and include `uvicorn` in `requirements.txt`

### ISSUE THREAD

**Issue by Vykp00** [google/yggdrasil-decision-forests#142] opened 2024-11-03 11:23 UTC
### Issue Description

I encountered some issues with the Dockerfile generated by the YDF model deployment tool. I run `model.to_docker`, the generated Dockerfile cannot start a container:

   Currently, the generated Dockerfile uses:
   ```dockerfile
   CMD ["fastapi", "run", "main.py", "--port", "8080"]
   ```
   This command doesn't work because FastAPI does not have a `run` command. Instead, to run a FastAPI application, the `uvicorn` ASGI server should be used.

   **Suggested Change**:
   ```dockerfile
   CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
   ```
   This assumes that the FastAPI app is defined as `app` in `main.py`. This change will make the Dockerfile compatible with FastAPI applications.

   The generated `requirements.txt` does not include `uvicorn`, which is required to run FastAPI applications. Adding `uvicorn` to `requirements.txt` will ensure the generated Dockerfile works as expected out of the box.

   **Suggested Addition**:
   ```plaintext
   uvicorn
   ```

**My Environment**
OS: Ubuntu 22.04.5 LTS
Yggdrasil Decision Forests Version:  0.8.0

**Comment by rstz** [comment] 2024-11-04 09:08
Hi, this looks like a duplicate of https://github.com/google/yggdrasil-decision-forests/issues/137 which is fixed and will be included in the next release. Please reopen if this is not the case.

**Closed by rstz** 2024-11-04 09:08 UTC
